### ISSUE TITLE
after run comman  i got error.how to fix ?

### ISSUE THREAD

**Issue by JANGFREEMAN** [jamesbachini/DEX-Arbitrage#12]
ProviderError: Out Of Fund
    at HttpProvider.request (/Users/zyx/Desktop/github/contract/DEX-Arbitrage/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at LocalAccountsProvider.request (/Users/zyx/Desktop/github/contract/DEX-Arbitrage/node_modules/hardhat/src/internal/core/providers/accounts.ts:182:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jamesbachini** [comment]
Maybe no eth to pay gas fees in the .env wallet? Aurora added a gas fee since I made the tutorial. On other networks you would still need some native asset in that .env wallet. i.e. BNB for Binance smart chain, FTM for fantom etc.
