### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'balance')

### ISSUE THREAD

**Issue by h6561105** [jamesbachini/DEX-Arbitrage#3]
I removed some of the baseAssets and I get this error message when I try to run trade.js,  and also how do I transfer WETH into aurora?

TypeError: Cannot read properties of undefined (reading 'balance')
    at lookForDualTrade (I:\aurora2\DEX-Arbitrage\scripts\trade.js:52:50)
    at lookForDualTrade (I:\aurora2\DEX-Arbitrage\scripts\trade.js:64:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at lookForDualTrade (I:\aurora2\DEX-Arbitrage\scripts\trade.js:64:7)
    at main (I:\aurora2\DEX-Arbitrage\scripts\trade.js:19:3)

**Comment by DDecoene** [comment]
Paste your config and I will look at it

**Comment by jamesbachini** [comment]
Looks like a zero balance issue. Make sure the contract has at least one base asset to trade and is holding an amount of those funds. You can get WETH by wrapping ETH for WETH (Wrapped ETH) on Trisolaris. The team has implemented a transaction fee now unfortunately so you need some ETH in your main account to pay gas fees. You can get a tiny amount of ETH from https://aurora.dev/faucet for larger amounts use one of the bridges. Trisolaris has a list of them.

**Comment by slawton3** [comment]
I am getting this issue as well. I made sure the contract and owner has enough eth for gas. Was anyone able to find a solution to this?

Here's my config for Aurora:

```
  "arbContract": "**contract-redacted**",
  "minBasisPointsPerTrade": 0,
  "routers": [
    { "dex": "trisolaris", "address": "0x2CB45Edb4517d5947aFdE3BEAbF95A582506858B" },
    { "dex": "wannaswap", "address": "0xa3a1ef5ae6561572023363862e238afa84c72ef5" },
    { "dex": "auroraswap", "address": "0xA1B1742e9c32C7cAa9726d8204bD5715e3419861" }
  ],
  "baseAssets": [
    { "sym": "weth","address": "0xC9BdeEd33CD01541e1eeD10f90519d2C06Fe3feB" },
    { "sym": "wnear", "address": "0xC42C30aC6Cc15faC9bD938618BcaA1a1FaE8501d" },
    { "sym": "aurora", "address": "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79" },
    { "sym": "usdc", "address": "0xB12BFcA5A55806AaF64E99521918A4bf0fC40802" }
  ],
```

Error:
```
undefined
TypeError: Cannot read properties of undefined (reading 'balance')
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:75:46)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:9)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:9)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:76:5)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:9)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:9)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:66:9)
    at lookForDualTrade (C:\Users\Sean\dev\DEX-Arbitrage\scripts\trade.js:76:5)


//logged the token after
{
  sym: 'wnear',
  balance: BigNumber { value: "7000000000000000000000000" },
  startBalance: BigNumber { value: "7000000000000000000000000" }
}
```

**Comment by jamesbachini** [comment]
Maybe the wannaswap address doesn't have the right checksum (all lowercase)?

Can't see why that would affect it though. Assume you didn't change anything in trade.js?

Would definitely double check all the addresses on a block explorer if that is all you've modified

**Comment by zikkuratti** [comment]
got the same

**Comment by slawton3** [comment]
I've narrowed it down to the following:

It looks like the trade.js file is looking for the USDT and UST stablecoin addresses in the balances object under the target route.

This is returning undefined:
```
balances[targetRoute.token1]
```
 I've removed these from the aurora config file and am trying to figure out why these addresses are being assigned to the target route config

**Comment by zikkuratti** [comment]
@slawton3 yep or just comment out this exception log) it's work
