### ISSUE TITLE
Error: network does not support ENS

### ISSUE THREAD

**Issue by takec0418** [jamesbachini/DEX-Arbitrage#36]
I can deploy the contract, but when I try to run this step:
npx hardhat run --network aurora .\scripts\trade.js
I get this error:

Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.5.2)
    at Logger.makeError (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at EthersProviderWrapper.<anonymous> (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1675:20)
    at step (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)
    at fulfilled (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'network does not support ENS',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'ENS',
  network: 'unknown'
}

Maybe I am just doing something wrong?

Thanks in advance.

**Comment by jamesbachini** [comment]
Sounds like there is a contract address missing or incorrectly formatted. Make sure everything is set in the config file and checksums are correct (not all lower case)

**Comment by takec0418** [comment]
Thank you for your response. Upon reviewing, I was able to execute it, but a new error has occurred

Loaded 171 routes
Owner: 0x9bE889B019462227E38272955A0c6808616eb56A
weth 0
wnear 0
usdt 0
aurora 0
atust 0
usdc 0
Error: call revert exception (method="estimateDualDexTrade(address,address,address,address,uint256)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Interface.decodeFunctionResult (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\abi\src.ts\interface.ts:425:23)
    at Contract.<anonymous> (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\contracts\src.ts\index.ts:392:44)
    at step (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (C:\Users\管理\Desktop\bot\DEX-Arbitrage\DEX-Arbitrage\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'estimateDualDexTrade(address,address,address,address,uint256)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x9bE889B019462227E38272955A0c6808616eb56A',
  args: [
    '0xA1B1742e9c32C7cAa9726d8204bD5715e3419861',
    '0xa3a1ef5ae6561572023363862e238afa84c72ef5',
    '0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79',
    '0xb12bfca5a55806aaf64e99521918a4bf0fc40802',
    BigNumber { value: "0" }
  ],
  transaction: {
    data: '0x068e7ca1000000000000000000000000a1b1742e9c32c7caa9726d8204bd5715e3419861000000000000000000000000a3a1ef5ae6561572023363862e238afa84c72ef50000000000000000000000008bec47865ade3b172a928df8f990bc7f2a3b9f79000000000000000000000000b12bfca5a55806aaf64e99521918a4bf0fc408020000000000000000000000000000000000000000000000000000000000000000',
    to: '0x9bE889B019462227E38272955A0c6808616eb56A',
    from: '0x9bE889B019462227E38272955A0c6808616eb56A'
  }
}

Is it necessary for the funds to be in the Aurora chain, even though they are in MetaMask?

**Comment by jamesbachini** [comment]
Yes metamask is a digital wallet. Aurora is a blockchain. If you have mainnet Eth that's on a totally separate network
